README.md

Fill out draft of contributing section

---

.flowconfig
definitions/globals.js
docs/sketch.md
package.json
src/index.js
src/sketch.js
website/sidebars.json

Note: This branch is based off `sketch-compat` – if the branch gets merged first the base needs changing.

Sketch Utility Methods

---

package.json
src/AbstractAPI/__snapshots__/test.js.snap
src/AbstractAPI/index.js
src/AbstractCLI/__snapshots__/test.js.snap
src/AbstractCLI/index.js
src/AbstractCLI/test.js
src/Client/index.js
website/static/css/custom.css
website/static/img/logo.svg
yarn.lock

These changes allow the SDK to run in the environment of a Sketch plugin.

Sketch Plugin Compatability

---

docs/reference.md
package.json
src/AbstractAPI/__snapshots__/test.js.snap
src/AbstractAPI/index.js
src/AbstractAPI/test.js
src/index.js.flow

This pull request adds support for `activities.list` to the API transport.
Refs #21

API: Initial support for activity lists

---

docs/reference.md
src/AbstractAPI/__snapshots__/test.js.snap
src/AbstractAPI/index.js
src/AbstractAPI/test.js
src/index.js.flow

This pull request adds support for `notifications.list` to the API transport.
Refs #20

API: Initial support for notification lists

---

docs/reference.md

This pull request adds documentation for `changesets.info`.
Resolves #31

feature: document changesets.info

---

docs/authentication.md

Feature has been flipped, this route and menu item are now visible to all teams.
closes https://github.com/goabstract/abstract-sdk/issues/57

Remove Google Form from SDK access

---

CHANGELOG.md

This pull request updates the change log for the latest `0.6.0` releasee.

feature: update changelog

---

docs/abstract-api.md
docs/installation.md
website/package.json

1.4.0 -> 1.7.1
Not much from what I can tell
- Support for another level of categories
- Fixed weird 1px header gap on mobile
- 💅 
More details here: https://github.com/facebook/Docusaurus/blob/master/CHANGELOG.md

Upgrade docusaurus to 1.7.1

---

src/types.js

Updates layer share options to match the latest https://github.com/goabstract/ui/blob/0293b547b2a2911196f6d37e250cf8ccecd079bf/shared/src/types.js#L1167-L1172

Update LayerShare options to match latest

---

.flowconfig
flow-typed/npm/flow-bin_v0.x.x.js
flow-typed/npm/jest_v23.x.x.js
flow-typed/npm/lodash_v4.x.x.js
flow-typed/npm/prettier_v1.x.x.js
flow-typed/npm/query-string_v6.x.x.js
flow-typed/npm/uuid_v3.x.x.js
src/AbstractAPI/index.js
src/AbstractAPI/test.js
src/AbstractCLI/index.js
src/types.js

`0.7.0` of the SDK is [throwing flow errors downstream](https://circleci.com/gh/goabstract/ui/9248) because we have libdefs for things like lodash downstream that are missing in the SDK. When running flow in a downstream project the libdefs from that project are used to check the SDK

Add flow-typed modules

---

docs/abstract-api.md
src/AbstractAPI/__snapshots__/test.js.snap
src/AbstractAPI/index.js
src/AbstractAPI/test.js

For https://github.com/goabstract/abstract-sdk/issues/92
- Add `previews.url`
- Update `Preview.webUrl` to point to app.goabstract.com

Add previews.url

---

src/endpoints/Comments.js

This pull request updates the `comments.create` endpoint to no longer preload branches, layers, pages, or files before creating comments. This was previously required to gather information such as entity name, file type, etc., but this is no longer required after recent API updates.
Resolves #109

feature: do not preload entities when creating comments

---

docs/continuous-integration.md
website/sidebars.json

This pull request adds documentation on polling-based continuous integration and an example Slack integration.

feature: add polling-based CI documentation

---

.vscode/settings.json
abstract-sdk.d.ts
package.json
src/endpoints/Memberships.js
src/endpoints/Shares.js

This pull request adds an initial set of hand-rolled TypeScript definitions.
Fixes #26

feat: add hand-rolled TypeScript definitions

---

website/yarn.lock
yarn.lock

Addresses open security alerts.
`yarn upgrade && cd website && yarn upgrade`

chore: Upgrade dependencies

---

CONTRIBUTING.md

This pull request updates the contributor release documentation to account for a protected master branch.

chore: update release process documentation

---

abstract-sdk.d.ts
docs/abstract-api.md
docs/webhooks.md
src/types.js

New boolean is `true` if nobody has committed in this project yet.
Blocked on approval and deployment of API PR:
https://github.com/goabstract/projects/pull/3832

feat: Add 'isNew' boolean to project payload

---

docs/embed.md

This pull request updates the regular expression logic used by the embed code generator to be less brittle and to properly handle valid URLs with valid parameters.
References #212

fix: embed generator

---

abstract-sdk.d.ts
docs/abstract-api.md
package.json
src/endpoints/Collections.js
src/types.js
tests/endpoints/Collections.test.js

This pull request updates the `collections.list` endpoint to support the latest upstream query parameters.
References #210

feat: update collections list parameters

---

abstract-sdk.d.ts
docs/abstract-api.md
src/endpoints/Projects.js
src/types.js
tests/endpoints/Projects.test.js

This pull request updates the API transport by adding support for project creation, updating, deletion, archiving, and unarchiving.
Requires https://github.com/goabstract/projects/pull/3841
References #180

feat: support full project CRUD

---

package.json
src/endpoints/Branches.js
tests/endpoints/Branches.test.js

This pull request updates the branches endpoint to properly pass pagination query parameters.
Fixes #219

fix: support branch pagination

---

abstract-sdk.d.ts

fix: Type ErrorData in abstract-sdk.d.ts

---

abstract-sdk.d.ts
src/types.js

See https://github.com/goabstract/ui/pull/3017#discussion_r421828270.

chore: Add void to CommandOptions.shareId

---

package.json
website/siteConfig.js
website/static/js/marketo.js

Adds Marketo analytics to webpages, so our marketing team can learn more about our customers.

feat: add marketo analytics to documentation website

---

package.json
yarn.lock

Fixes an Error in node 14, regarding fs module.
Tested on node 10, 12, 14 and it works fine.
Issue #276

feat: update cli

---

abstract-sdk.d.ts
src/types.js

feat: Add 'type' to project type (this remains purposefully undocumented for now)

fix: Incorrect enum for project visibility

---

docs/abstract-api.md

Update `CommitDescriptor` docs to match implementation
Followup to https://github.com/goabstract/abstract-sdk/pull/173

Update CommitDescriptor docs

---

package.json
yarn.lock

fix: Add missing invariant to deps

---

docs/webhooks.md

Remove the beta notice from https://sdk.goabstract.com/docs/webhooks/

chore: Remove beta notice

---

.flowconfig
.github/workflows/core-checks.yml
package.json
yarn.lock

it fixes issues with deprecated octokit dependency

chore(deps): bump flow-typed from 2.5.1 to 3.8.0
