goabstract/abstract-sdk

- docs/reference.md
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractAPI/test.js
- src/index.js.flow
- src/support/factories.js
This pull request adds support for `activities.info` and `notifications.info`.
**Note:** This depends on goabstract/projects#915.
Resolves #20
Resolves #21
> API: Support activities.info and notifications.info

- docs/reference.md
This pull request updates the documentation for descriptor types with one property to be on a single line to save vertical space.
> API: Render descriptors with one property on a single line

- docs/reference.md
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractAPI/test.js
- src/index.js.flow
- src/support/factories.js
This pull request adds support for `comments.list` and `comments.info` to the API transport.
Resolves #30
> API: comments.list and comments.info

- docs/authentication.md
This pull request adds information around generating API tokens to the existing authentication documentation.
Resolves #42
> feature: add token information to auth docs

- docs/configuration.md
- src/AbstractAPI/index.js
- src/AbstractCLI/index.js
- src/Client/test.js
- src/index.js.flow
Current implementation only accepts a string:
```js
import * as Abstract from "abstract-sdk";
const abstract = Abstract.Client({
accessToken: process.env.ABSTRACT_API_TOKEN
});
```
New implementation accepts a function that returns a string:
```js
import * as Abstract from "abstract-sdk";
const abstract = Abstract.Client({
accessToken: () => Cookies.get("authToken")
});
```
Or a function that returns a promise of a string:
```js
import * as Abstract from "abstract-sdk";
const abstract = Abstract.Client({
accessToken: () => keytar.findPassword("abstract")
});
```
This is kind of a breaking change because the public-facing `Client` object has a public (but undocumented?) `accessToken` property that is currently a string but as of this PR is a function.
Should I add these use cases to the …
> Allow accessToken option to be a function

- docs/abstract-api.md
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractAPI/test.js
- src/index.js.flow
This pull request adds `organizations.info` support to the API transport.
Resolves #53
> feature: add organizations.info

- src/AbstractAPI/index.js
- src/AbstractCLI/index.js
- src/Client/index.js
- src/index.js.flow
> Fix issues with accessToken option function

- docs/pagination.md
- src/AbstractAPI/Cursor.js
- src/AbstractAPI/index.js
- src/index.js.flow
This pull request adds support for cursor-based pagination.
From a high level, a paginated list method should return a special `Promise` that contains a `next` method. The most obvious way to satisfy this requirement is to extend the built-in `Promise` class. Unfortunately, Flow doesn't support class method overloads, but does support interface method overloads; this means it's seemingly impossible to subclass Flow's own `Promise` type interface since it includes [an overloaded `then` definition](https://github.com/facebook/flow/blob/master/lib/core.js#L618-L626) that can't actually be implemented with type safety.
To overcome this limitation, a combination of interface inheritance and indirect type casting was used. A `CursorPromise` interface was created that implements the `Promise` …
> feature: add cursor-based pagination support

- docs/abstract-api.md
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractAPI/test.js
- src/index.js.flow
- src/support/factories.js
This pull request adds support for `users.list` and `users.info` to the API transport.
Requires https://github.com/goabstract/projects/pull/1133
Resolves https://github.com/goabstract/abstract-sdk/issues/55
> feature: add users.list and users.info

- docs/abstract-api.md
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractAPI/test.js
- src/AbstractCLI/__snapshots__/test.js.snap
- src/AbstractCLI/index.js
- src/AbstractCLI/test.js
Noticed this as I started to build something with the sdk. This is a holdover from when sha could be `undefined` to represent "latest". No test for this so it was missed 🙈
> Fix for commits.info(layer|file) at latest

- package.json
- src/AUTO/index.js
- src/AbstractAPI/Cursor.js
- src/AbstractAPI/index.js
- src/AbstractCLI/index.js
- src/Client/index.js
- src/index.js
- src/sketch.js
- src/support/factories.js
- src/types.js
- src/utils.js
- yarn.lock
We've had a bit of conversation about how we should enable external flow type checking when using this module, and although we're not in agreement quite yet, I am opening this PR for discussion of its merits and because it unblocks me in trying to incorporate this module into our projects.
By using `index.js.flow` as we would normally use a `types.js` file for all of our types, we end up _exporting_ our types, but they're not actually used when we import non-types. For instance, if you import
```js
import * as Abstract from "abstract-sdk";
```
`Abstract` is `any`.
Move the current `index.js.flow` to `types.js` and use [`flow-copy-source`](https://www.npmjs.com/package/flow-copy-source) to copy uncompiled source code to `lib`, suffixed with `.flow`. This way, when you import from …
> Copy flow files so that the module returns typed values

- docs/abstract-api.md
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractAPI/test.js
- src/types.js
This pull request adds `collections.update` and `collections.create` endpoints to the API transport.
**Note:** I wasn't totally sure if there was value in exposing these on the API transport since retuned collections are only a subset of what is or can be returned from the CLI. Happy to close this PR if we should table this until full collections can be built using only the API. We still have #71 to handle the CLI side of this.
Resolves #70
> feature: add collections.update and collections.create to API transport

- docs/abstract-api.md
- package.json
- src/AbstractAPI/__snapshots__/test.js.snap
- src/AbstractAPI/index.js
- src/AbstractCLI/index.js
- src/types.js
This pull request fixes an issue where the CLI would return different data than the API for `collections` methods. The CLI was returning collections along with file data, so to maintain parity, the API also returns file data as well (though the file data will only be populated if the user opts-in to avoid a performance hit.)
Fixes #79
> bugfix: consolidate API and CLI collection data

- src/errors.js
- src/index.js
This pull request exports our base error class as `Abstract.Error` so it can be used downstream in `instanceof` checks. This prevents consumers from needing to build an intersection type of all of our errors for Flow and prevents runtime `Error.name` checks.
> feature: export Abstract.Error

- .babelrc
- src/.browserslistrc
Confirmed the compiled files no longer contain `class` references:
Related https://github.com/goabstract/ui/pull/475
Related https://github.com/goabstract/ui/pull/486
> Introduce browserslistrc, ensure IE11 support

- .babelrc
As discussed in Slack, looks like this is also needed for the improved browser support. There appears to be no clear reason why I originally included this line – possibly copy/paste from the desktop app? 😬 
Related https://github.com/goabstract/JIRA/issues/5872
> Include transform-regenerator

- README.md
Instructions were incorrect – the actual publish is done on CI, and always should be.
> Remove publish step from README

- .circleci/config.yml
- package.json
- yarn.lock
This pull request moves `@elasticprojects/abstract-cli` from `peerDependencies` to `optionalDependencies` so that `abstract-sdk@0.7.x` can be installed externally without error.
References https://github.com/goabstract/abstract-sdk/issues/101
> bugfix: move CLI dependency from peer to optional

- package.json
- yarn.lock
This pull request adds a runtime dependency on [`@babel/runtime-corejs2`](https://babeljs.io/docs/en/babel-runtime-corejs2), which includes both `@babel/runtime` and `core-js`. Both of these are required as runtime dependencies when using certain Babel functionality ([reference](https://github.com/babel/babel/issues/9134#issuecomment-447666617), [reference](https://github.com/babel/gulp-babel/issues/50#issuecomment-255606255)).
This also moves `@elasticprojects/abstract-cli` back to a `peerDependency` since Yarn can't ignore `optionalDependencies` yet ([reference](https://github.com/yarnpkg/yarn/issues/5366). This made it so the SDK was not installable externally when using Yarn.
Fixes https://github.com/goabstract/abstract-sdk/issues/101
Fixes …
> bugfix: add required runtime babel dependencies

- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Data.test.js
- src/endpoints/Descriptors.js
- src/endpoints/Layers.test.js
- src/endpoints/Previews.test.js
- src/types.js
- src/utils.js
For https://github.com/goabstract/abstract-sdk/issues/76
- Revert descriptor types back to explicitly defined types. I originally avoided spread because I assumed the object descriptors wouldn't always be perfectly hierarchical like with the absence of pageId
- Added utility functions back to help explicitly convert objects into exact descriptors to avoid usage of `any`
- Added new utility for converting layer into `PageDescriptor` for commenting
- Updated `comments.create` so that when commenting on a layer `pageId` is loaded from the layer
- Remove `pageId` from `LayerDescriptor`
> Remove `pageId` from LayerDescriptor

- src/Client.js
This pull request updates the `Client` to check for a CLI executable in both `peerDependencies` and the macOS Abstract application folder.  This functionality existed before the reorganization in #98 and was lost in translation.
> bugfix: check peerDependencies and MacOS app folder for CLI

- .circleci/config.yml
- README.md
This pull request updates the the continuous integration script so that documentation is only deployed on pushes to the `docs` branch. This will allow documentation updates independently of `master` pushes or any release (NPM, git, or otherwise.) Note that this requires one extra step when cutting a new release: rebasing `master` on top of `docs` to pick up any typo fixes or changes made directly against the `docs` branch.
Resolves #62
> feature: deploy documentation on branch

- docs/abstract-api.md
This pull request fixes the documentation for retrieving an assets file by adding a missing `await` keyword to the example code.
> bugfix: update asset raw file documentation

- docs/abstract-api.md
- src/types.js
This pull request updates the SDK documentation and external type interfaces by removing references to both `email` and `billingEmail`. Both of these fields will no longer be returned by the API.
> bugfix: remove email addresses from documentation and type interfaces

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
This pull request updates the `README` and adds a simple `CONTRIBUTING` guide. It's mostly a reorganization of existing information (moving contribution-specific content to a contributor-specific file to keep the `README` simple) with a few corrections after recent changes.
> feature: update README and add CONTRIBUTING guide

- docs/abstract-api.md
- src/Client.js
- src/endpoints/Memberships.js
- src/endpoints/Memberships.test.js
- src/types.js
This pull request adds a new `Memberships` endpoint with API transport support.
Requires https://github.com/goabstract/projects/pull/1977
References #108
> feature: add memberships endpoint to the API transport

- docs/abstract-api.md
This pull request adds missing documentation for the `projects#list` endpoint and its supported parameters.
Fixes #121
> bugfix: add missing projects endpoint documentation

- docs/configuration.md
- src/Client.js
- src/Client.test.js
- src/endpoints/Activities.js
- src/endpoints/Assets.js
- src/endpoints/Branches.js
- src/endpoints/Changesets.js
- src/endpoints/Collections.js
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Data.js
- src/endpoints/Endpoint.js
- src/endpoints/Files.js
- src/endpoints/Layers.js
- src/endpoints/Memberships.js
- src/endpoints/Notifications.js
- src/endpoints/Organizations.js
- src/endpoints/Pages.js
- src/endpoints/Previews.js
- src/endpoints/Projects.js
- src/endpoints/Shares.js
- src/endpoints/Users.js
- src/testing.js
- src/types.js
- yarn.lock
This pull request implements an entity cache for static response values, or response values that will never change over time. This is especially useful for methods that always return the same entity based on a given descriptor (like `info` methods), whereas methods that inherently can't be cached since they must return up-to-date, dynamic data reap no benefit (like `list` methods).
The cache was implemented as a decorator and makes use of aspect-oriented programming to wrap normal requests at runtime.
Resolves #87
> feature: implement decorator-based entity cache

- package.json
This pull request removes `abstract-cli` from the dependency list since this is only sort of useful for internal SDK usage (and even then, a custom `cliPath` is almost always used.) This also allows the SDK to be externally installed without skipping peer or optional dependencies, which was reported via support.
> bugfix: remove abstract-cli dependency

- docs/abstract-api.md
- src/endpoints/Data.js
- src/types.js
This pull request brings the `LayerData` type up to parity with core's `LayerData` type. I noticed these discrepancies while working on embeds: I attempted to use a `LayerIcon` component that uses internal functions typed to core's `LayerData` with `LayerData` returned from the SDK.
> bugfix: add missing LayerDataAsset type

- src/endpoints/Shares.js
Shares api v13 automatically resolves the placeholder `{sha: "latest"}` to the layer's _last changed at sha_ `{sha: "abc123"}`.
This is considered a breaking change for any clients depending on the placeholder (this was true for certain internal use cases). 
We'd like to land this in pre-release to coordinate with the internal deprecation of the placeholder.
> feat(Shares): upgrade to api v13

- CHANGELOG.md
- docs/abstract-api.md
- src/endpoints/Activities.js
- src/endpoints/Assets.js
- src/endpoints/Branches.js
- src/endpoints/Changesets.js
- src/endpoints/Collections.js
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Data.js
- src/endpoints/Files.js
- src/endpoints/Layers.js
- src/endpoints/Memberships.js
- src/endpoints/Notifications.js
- src/endpoints/Organizations.js
- src/endpoints/Pages.js
- src/endpoints/Previews.js
- src/endpoints/Projects.js
- src/endpoints/Shares.js
- src/endpoints/Users.js
- src/types.js
- src/utils.js
This pull request does the following:
- Modifies all `raw` methods to save to disk by default (per @tommoor)
- Adds `RawOptions` to allow opting-out of disk saving and specifying a custom filename
- Adds `files.raw` support to the CLI transport
- Cleans up duplicated of return types in each endpoint
- Updates documentation so API and CLI indicators are per-method, not per-endpoint
Resolves https://goabstract.atlassian.net/browse/PLATFORM-248
> feature: add files.raw to the CLI transport

- src/endpoints/Commits.js
- src/endpoints/Commits.test.js
This pull request updates the `commits.info` endpoint to search for and return individual commits by `sha` instead of arbitrarily using the first commit that's returned from `commits.list`.
Fixes https://github.com/goabstract/abstract-sdk/issues/133
> bugfix: find single commit by sha

- src/endpoints/Commits.js
- src/endpoints/Commits.test.js
This pull request updates `Commits#info` to use the [newly-supported API endpoint](https://github.com/goabstract/projects/pull/2345) for commit retrieval instead of relying on `Commits#list`.
Resolves https://goabstract.atlassian.net/browse/PLATFORM-358
> feature: use API show action for commits

- docs/embed.md
- src/endpoints/Pages.js
- src/endpoints/Pages.test.js
- website/sidebars.json
This pull request updates the CLI transport by adding support for `Pages#list` and `Pages#info`. It also updates embed documentation and adds this to the sidebar now that this feature is public.
Resolves https://goabstract.atlassian.net/browse/PLATFORM-376
Resolves #134
> feature: add pages endpoint to CLI transport

- package.json
- src/Client.js
- src/endpoints/Endpoint.js
- src/endpoints/Previews.js
- src/testing.js
- src/types.js
- yarn.lock
To support desktop's async config https://github.com/goabstract/ui/pull/1215 we need to allow for `previewsUrl` to be async
I went ahead and updated `previewsUrl` and the remaining configs that may be used asynchronously one day. Was straight forward because everywhere these options are used were already async 👍 
- Change `previewsUrl`, `apiUrl`, 'webUrl', and `cliPath` to `string | Promise<string>`
- Upgrade flow to asssit with suppressing spread bug with unions and to match the  ui version
> feat: Allow async endpoint options

- src/endpoints/Collections.js
- src/endpoints/Collections.test.js
As of abstract-cli 2.0, the abstract-cli responses for collections match the structure of the API's responses. This PR updates the collection's `list` and `info` functions to use the new structure.
> chore: update cli collection endpoints to use abstract-cli 2.0 response schema

- docs/sketch-api.md
Documentation has sketch with a capital S, therefore returning undefined when using these examples.
Changed casing of Abstract.Sketch to Abstract.sketch to match api
> fix: update Sketch documentation

- docs/abstract-api.md
I noticed the File object now comes with a (very useful) `updatedAt` field. I'm raising this to document it in the APIs.
> docs: Document the `updatedAt` field in the File object

- docs/abstract-api.md
`Retrieve an Sketch file` → `Retrieve a Sketch file`.
Note that this will break any permalinks to the header.
> docs: Fix a typo in the Files API documentation

- src/endpoints/Files.js
Exporting files using the CLI works successfully for me, but I noticed that the client doesn't actually wait until they've finished exporting — it just kicks it off. This is problematic, because there's no real good way for a client application to check if the file has been exported in time, other than waiting (which might be really long if there are a lot of files in the export!).
It seems like this request was always intended to be `await`ed, since the method itself is `async`. Otherwise, could you provide some guidance or workaround for this issue? Does it need to be fixed on the CLI itself?
> fix: Await the CLI request in files.raw

- package.json
This pull request excludes test-related files from `flow-copy-source` used during the `prebuild` task.
References: https://goabstract.atlassian.net/browse/PLATFORM-490
> fix: ignore test files when generating typings

- src/endpoints/Branches.js
- src/endpoints/Collections.js
- src/endpoints/Comments.js
- src/endpoints/Organizations.js
- src/endpoints/Pages.js
- src/endpoints/Projects.js
- src/endpoints/Users.js
This pull request removes caching from non-static endpoints. This was a total oversight and could result in stale, cached entities being returned instead of the most up-to-date version.
After this change, the entity types below are the only ones that we'll cache (since they are all either static or requested using a static `sha`):
```
Activity
Asset
Changeset
Commit
Data
File
Layer
Membership
Notification
Preview
Share
```
References https://goabstract.atlassian.net/browse/PLATFORM-490
> fix: disable caching of non-static entities

- docs/abstract-api.md
This PR removes the `pageId` from `LayerDescriptor` examples since we do not use it anymore.
> fix: remove pageId from LayerDescriptor examples

- abstract-sdk.d.ts
- src/types.js
This value was never documented and we're going to stop sending it down from the server shortly.
> chore: Remove undocumented project.userIds from types

- docs/embed.md
Just noticed this little detail
> fix: embed documentation typo &chromless -> ?chromeless

- package.json
- src/endpoints/Endpoint.js
- yarn.lock
Bumps flow-bin to v0.110.1 and fixes one resulting flow error, which seems like it won't cause any issues in projects that depend on abstract-sdk.
> chore: upgrade flow to 110

- package.json
The way we require abstract-cli doesn't work with webpack in browser environments. This change fixes webpack builds that use abstract-sdk. Thanks @amccloud for this suggestion.
> fix: don't require abstract-cli in the browser

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Commits.test.js
- src/endpoints/Data.js
- src/endpoints/Layers.js
- src/endpoints/Previews.js
- src/types.js
This pull request fixes the `commits.list` method by updating its signature accordingly. To help accomplish this, the existing `LayerDescriptor` was updated to be `sha`-less, and a new `LayerVersionDescriptor` was added for cases where a `sha` is actually required, which is still most cases.
> fix: update commits.list method signature

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Assets.js
- src/endpoints/Changesets.js
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Descriptors.js
- src/endpoints/Files.js
- src/types.js
- tests/endpoints/Commits.test.js
BREAKING CHANGES
Depends on deployment of new API endpoint: https://github.com/goabstract/projects/pull/3735
> feat: Remove need to pass branchId to load a commit

- abstract-sdk.d.ts
- src/endpoints/Commits.js
- tests/endpoints/Commits.test.js
Note: The documentation already listed the camelCased version: https://sdk.abstract.com/docs/abstract-api/#list-all-commits
> fix: Incorrect casing on commits.list parameters

- package.json
This pull request fixes an issue where `js-sh256` was specified as a `devDependency` instead of a `dependency`.
Fixes #177
> fix: move js-sha256 from devDependencies to dependencies

- CHANGELOG.md
- package.json
This pull request cuts `abstract-sdk@7.0.1` which includes a dependency fix.
> chore(release): 7.0.1

- src/endpoints/Activities.js
- src/endpoints/Assets.js
- src/endpoints/Branches.js
- src/endpoints/Changesets.js
- src/endpoints/CollectionLayers.js
- src/endpoints/Collections.js
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Data.js
- src/endpoints/Endpoint.js
- src/endpoints/Files.js
- src/endpoints/Layers.js
- src/endpoints/Memberships.js
- src/endpoints/Notifications.js
- src/endpoints/Organizations.js
- src/endpoints/Pages.js
- src/endpoints/Previews.js
- src/endpoints/Projects.js
- src/endpoints/Sections.js
- src/endpoints/Shares.js
- src/endpoints/Users.js
- src/endpoints/Webhooks.js
- src/types.js
- tests/Client.test.js
This pull request is a little housekeeping to consolidate the signature for `Endpoint#configureRequest`. Rather than pass in one argument for endpoint configuration and another for request configuration, everything is passed as one configuration object.
**Note:** Almost all of the changes in this PR are formatting from Prettier, so it's best to hide whitespace changes when viewing it. Flow also strongly types all of the actual code changes here, which should help the review.
> fix: move request options internally

- package.json
This pull request cuts `abstract-sdk@8.0.0-beta.0` which includes an update to changeset responses.
> chore(release): 8.0.0-beta.0

- package.json
This pull request removes support for Node 8 since [its end of life date is 12/31/2019](https://nodejs.org/en/about/releases/). This means that asynchronous iteration support will no longer have to be down-emitted, which will fix the `core-js` issues reported in #186.
References #186
> feat!: remove support for node 8

- package.json
This pull request cuts `abstract-sdk@8.0.0-beta.1` which removes Node 8 support and in turn fixes a reported `core-js` issue (#186).
> chore(release): 8.0.0-beta.1

- package.json
This pull request cuts `abstract-sdk@8.0.0-beta.2` which adds a new `isNew` property to `Project`.
> chore(release): 8.0.0-beta.2

- src/endpoints/Branches.js
- src/endpoints/Commits.js
- tests/Client.test.js
- tests/endpoints/Branches.test.js
fix: Commits list api endpoint (broken in v8 prerelease)
fix: Ensure policies are returned in unwrapped branches payload
> fix: Ensure policies are returned in branches payload

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Branches.js
- src/endpoints/Commits.js
- src/errors.js
- tests/endpoints/Branches.test.js
This pull request updates the `branches.list` endpoint to support name-based searches when using the API transport.
References #202 
Requires https://github.com/goabstract/projects/pull/3891
> feat: support branch searching

- src/endpoints/Data.js
- tests/endpoints/Data.test.js
When using the cli transport for layer data, the following error is getting bubbled up from `abstract-sdk`:
> Error runtime error: index out of range [4] with length 4 ### CLI command: abstract-cli layer data [projectId] [sha] [fileId] [layerId]
We aren't currently passing in a branch id, even though the version of abstract-cli we depend upon uses it.
> fix: pass branch id to cli for data endpoint

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Layers.js
- tests/endpoints/Layers.test.js
Depends on https://github.com/goabstract/projects/pull/3894, posting the same explanation here for visibility
This adds two new filtering options for layers:
- `excludeLibraryDependencies` - this will make it so that symbols from external libraries are not included in the list of layers. These are the items that we show as "dependencies" in the file list and aren't shown by default unless you click on them.
- `onlyLibraryDependencies` - the opposite of `excludeLibraryDependencies`. You can choose this option if you need to load the library dependencies separately.
These options should help our pagination of layers be a little more intuitive so that we don't load pages of data that aren't even shown in the screen you're looking at.
> feat: add layer dependency filtering options

- package.json
- src/endpoints/Layers.js
- tests/endpoints/Layers.test.js
- yarn.lock
Depends on https://github.com/goabstract/projects/pull/3929 and a new version of abstract-cli being released
This PR adds filtering options to `layers.list` for the `cli` transport so that that same filtering options are available as the `api` transport. Previously, sdk would allow you to pass filtering options but would ignore them for the `cli` transport.
Documentation should already be up-to-date since we already support these options for the `api` transport.
> feat: add layer filtering options to cli transport

- src/endpoints/Branches.js
- src/endpoints/Commits.js
- src/endpoints/Files.js
- tests/Client.test.js
- tests/endpoints/Branches.test.js
- tests/endpoints/Commits.test.js
- tests/endpoints/Files.test.js
Fairly straightforward PR. We deprecated a certain amount of commands in the CLI those last 6 to 12 months, this PR makes sure we're no longer using them.
> refactor: stop using deprecated CLI commands

- src/index.js
- src/util/helpers.js
- tests/util/helpers.test.js
Share links with the abstract.com domain should be considered valid. This PR updates the `parseShareURL` function to allow this domain.
I made a similar update in https://github.com/amccloud/storybook-addons-abstract/pull/6. In that PR, @amccloud [made the suggestion](https://github.com/amccloud/storybook-addons-abstract/pull/6#discussion_r372511342) that we expose `inferShareId` since he manually copied it into the package, so I've also done that in this PR 🙂
> fix: Allow abstract.com domain for share links and expose inferShareId

- src/endpoints/Collections.js
- src/types.js
This PR adds the ability to use a custom api version on the collections request. 
Part of https://github.com/goabstract/projects/pull/4159
Project reference: https://github.com/goabstract/ui/pull/2451
> chore: add custom api version to collections request

- src/endpoints/Changesets.js
- src/endpoints/Collections.js
- src/endpoints/Data.js
- src/endpoints/Layers.js
- tests/endpoints/Changesets.test.js
- tests/endpoints/Collections.test.js
- tests/endpoints/Data.test.js
- tests/endpoints/Layers.test.js
This PR is pretty basic, it just replaces some CLI commands that are deprecated by the new ones.
The affected commands are `layer`, `collection`, and `changeset`
> chore(cli): replace deprecated usages

- CHANGELOG.md
- package.json
This PR cuts `abstract-sdk@8.0.0-beta.13` - please see [changelog](https://github.com/goabstract/abstract-sdk/pull/223/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e).
> chore(release): 8.0.0-beta.13

- package.json
- src/endpoints/Endpoint.js
- yarn.lock
Integration tested with the ui project.
This flag being enabled essentially restores operations to how they were prior to CLI 4.3 where no automatic clone/fetch operations will be performed for read commands.
> chore: skip-network-read-ops flag

- package.json
As a production dependency this is getting unnecessarily bundled in host applications.
> chore: Move flow-typed to a dev dependency

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Branches.js
- src/types.js
- tests/endpoints/Branches.test.js
Adds the ability to query the branch merge state for both the API and CLI transports.
Note that CLI only provides the `state` while the API returns more detailed information.
> feat: branches merge state

- docs/abstract-api.md
- src/endpoints/Branches.js
- tests/endpoints/Branches.test.js
When testing this in the front end, I noticed that an API call was always fired when accessing a branch's merge state, even when passing `transportMode: ["cli"]`. This PR fixes the issue by including `RequestOptions` in the endpoint declaration.
I also changed the `parent` parameter to `parentId`. It felt more intuitive to me, but if we don't want to make that change I can easily revert.
> fix: Respect transportMode for branches.mergeState

- src/endpoints/Branches.js
- tests/endpoints/Branches.test.js
The CLI returns a branch's merge state nested under a `data` key. This PR updates the SDK so we return the merge state directly (which is the expected response according to the docs).
> fix: Return branch merge state at top level of CLI response

- .github/no-response.yml
Enables probot [no response](https://github.com/probot/no-response), which will close issues labelled `more-information-needed` where the original author does not reply with required info.
The app has already been installed for this repo.
> chore: probot no-response config

- abstract-sdk.d.ts
- src/types.js
- The API change for `user.lastActiveAt` will be deployed to production shortly
- `membership.subscriptionRole` has existed for a long time
> feat: Add missing properties to user/membership types

- abstract-sdk.d.ts
- src/endpoints/Activities.js
- src/endpoints/Assets.js
- src/endpoints/Branches.js
- src/endpoints/Changesets.js
- src/endpoints/CollectionLayers.js
- src/endpoints/Collections.js
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Data.js
- src/endpoints/Endpoint.js
- src/endpoints/Files.js
- src/endpoints/Layers.js
- src/endpoints/Memberships.js
- src/endpoints/Notifications.js
- src/endpoints/Organizations.js
- src/endpoints/Pages.js
- src/endpoints/Previews.js
- src/endpoints/Projects.js
- src/endpoints/ReviewRequests.js
- src/endpoints/Sections.js
- src/endpoints/Shares.js
- src/endpoints/Stars.js
- src/endpoints/Users.js
- src/endpoints/Webhooks.js
- src/types.js
- tests/endpoints/Activities.test.js
- tests/endpoints/Endpoint.test.js
Adds a callback option to `Client` so you can receive data about each endpoint called in the sdk which will enable us to compare execution times for api vs. cli requests for quick sync:
I'll leave some comments inline.
Part of https://goabstract.atlassian.net/browse/PLATFORM-1029
> feat: allow observing analytics on endpoints

- src/endpoints/Pages.js
- tests/endpoints/Pages.test.js
Switch to using `abstract-cli files list` to get the pages instead of `abstract-cli files`.
> fix: Prefer "files list" over deprecated "files".

- abstract-sdk.d.ts
- src/Client.js
- src/endpoints/Endpoint.js
- src/types.js
This is a follow-up to https://github.com/goabstract/abstract-sdk/pull/242. We have a need to be able to set the analytics callback separately between desktop and web, so we need to be able to set it outside of the constructor. This PR maintains the same ability to pass it as part of the constructor, but also be able to set the callback directly on `Client`.
> feat: allow analytics callback to be set on Client

- docs/abstract-api.md
Another little doc issue I noticed today. If you have a  `LayerDescriptor` with a `sha` you have a `LayerVersionDescriptor`
> chore(docs): Remove optional sha from LayerDescriptor

- docs/abstract-api.md
- `symbolId` is a UUID to symbol master
- `symbolId` is defined on layers when type: `symbolInstance` and `symbolMaster`
- `symbolId` on a symbol master is self-referential
> chore(docs) symbolId is UUID to symbol master

- src/endpoints/Endpoint.js
Proposing an alternate solution to https://github.com/goabstract/abstract-sdk/pull/251, since we're not sure if node's `perf_tools` module is going to work in the browser. We know that this will give us what we need for the internal analytics reporting, and doing it this way won't break for node users. If we need to make this public in the future, we can find a way to use either `perf_tools` or `window.performance` depending on whether the consumer is a browser or a node environment, but I think this is probably what we need for now.
> fix: only use performance.now when it is available

- src/endpoints/Collections.js
The API including `branches` as part of the `collections#index` response is being put behind an API version (https://github.com/goabstract/projects/pull/4521). This PR bumps the API version for that call to the API.
> chore: use api version 25 for collection lists

- src/endpoints/Branches.js
- tests/endpoints/Branches.test.js
In the below PR "active" was replaced with "workedOn" for the CLI only. Because we still use "active" with the API the SDK seems to be the correct place to normalize this.
reference: https://github.com/goabstract/projects/pull/4013
> fix: 'active' filter with latest CLI only filters to specifically active branches

- src/endpoints/Endpoint.js
Fixes the error from `8.0.0-beta.20` regarding:
```
api: ReferenceError: performance is not defined
at makeRequest (project/node_modules/abstract-sdk/dist/endpoints/Endpoint.js:79:25)
```
> fix: Add perfomance from  perf_hooks (Node v8.5.0+)

- src/endpoints/Endpoint.js
Closes https://github.com/goabstract/abstract-sdk/issues/243
Changes `performance` to be used directly on the `window` object, if it exists, rather than assuming we can access it as a global variable.
> fix: undefined 'performance' in node environments

- src/endpoints/Collections.js
Bumping the collections api to 26. This will likely need to be coordinated alongside release 92.
Reference: https://github.com/goabstract/ui/pull/2939
> chore: bump collections api to 26

- src/errors.js
- Do not try to capture stack trace when `Error.captureStackTrace` is not available
Fixes https://sentry.io/organizations/elastic-projects/issues/1633606217/?project=103885
> fix: Optional Error.captureStackTrace

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Shares.js
- src/types.js
- src/util/helpers.js
In order to access the `shareId` prop in the `ui` project, we need to remove its union to `{| url: string |}` in the `ShareDescriptor` type. The url part was moved to a brand new `ShareUrlDescriptor`.
Will be updating accordingly the `ui` project right after this gets approved starting with this [PR](https://github.com/goabstract/ui/pull/2985).
> refactor: moves url param to ShareUrlDescriptor

- abstract-sdk.d.ts
- docs/configuration.md
- src/endpoints/Endpoint.js
- src/types.js
- tests/Client.test.js
We recently ran into an issue where some requests on private share link pages would fail because we were only allowing a single `accessToken`. For these share links, `accessToken` was being set to the share ID, and the authentication header would never get configured.
This PR adds a separate `shareId` option that can be set in addition to the `accessToken`, allowing both headers to exist on a request.
> feat: Add ability to set a shareId

- src/endpoints/Endpoint.js
It is unlikely, but possible for the CLI to respond with something that is not JSON-parsable. Currently if this happens an uncaught error is thrown. In our applications this would result in a request that is never resolved.
This change makes sure that the error is caught and the promise is properly rejected.
> fix: Correctly handle error when CLI response is unparsable

- abstract-sdk.d.ts
- docs/abstract-api.md
- src/endpoints/Organizations.js
- src/types.js
In order to make API requests more performant we no longer return feature flags inside of organization payloads.
> chore: Remove features from organizations response

- docs/embed.md
Embeds for private shares authenticate as expected if you are logged into abstract.com https://github.com/goabstract/ui/pull/3068
Example from Abstract org:
https://app.abstract.com/embed/09c340f4-476f-41e0-8247-22795d57ec95
> docs: Update embed docs for public shares

- CONTRIBUTING.md
This PR updates the documentation for the steps to take for cutting a new release + fixes the broken footer image link:
> chore: update release process checklist for contributing

- src/endpoints/Projects.js
Using version >= 22 to ensure that the repo is created on the server and does not require the desktop app, which makes a lot of sense for the SDK 😉
> fix: Update API version passed to project create/update

- src/endpoints/Endpoint.js
- src/errors.js
- tests/Client.test.js
- tests/errors.test.js
Validation errors are one of the most common error types, yet we weren't giving it it's own class/handler.
Also no longer throws `MultiError` when only a single transport is used. 
closes #279
> fix: Add ValidationError class

- src/endpoints/Endpoint.js
- tests/Client.test.js
- tests/endpoints/Branches.test.js
- tests/endpoints/Files.test.js
- tests/endpoints/Pages.test.js
- tests/errors.test.js
- tests/util/helpers.test.js
Error handling was totally broken by this PR: https://github.com/goabstract/abstract-sdk/pull/301 – and subsequently in the last beta release.
If a single transport is chosen and a single error happens the error handler is never called, instead you get an empty response in the success handler.
See comments for more details.
> fix: Broken error handling

- README.md
Fixes the broken wordmark image in `README.md`.
> fix: Broken wordmark image in README

- package.json
- yarn.lock
Update to CLI [12.2.0](https://www.npmjs.com/package/@elasticprojects/abstract-cli/v/12.2.0)
> chore(cli): bump to 12.2.0

- CHANGELOG.md
- abstract-sdk.d.ts
- docs/abstract-api.md
- package.json
- src/endpoints/Branches.js
- src/types.js
- tests/endpoints/Branches.test.js
To make web and desktop actions work seamlessly as it relates to updating branches ([ABS-2988](https://goabstract.atlassian.net/browse/ABS-2988)), we figured it was a good move to plumb an `update` method to our SDK now that we have the server-side api endpoint available.
This change will allow us to move the `BranchUpdateRequest` to core since we'll be able to perform this request from the SDK.
> feat: adds update method to Branch endpoint

- CHANGELOG.md
- package.json
Follow up of https://github.com/goabstract/abstract-sdk/pull/309.
> "chore(release): 8.0.0-beta.38"

- package.json
As suggested in comments of linked PR
> fix: Mark stream dependency as node-only

- README.md
- website/siteConfig.js
This updates the documentation to not reference a deprecated spectrum community. Now links won't direct you to a location we don't own or maintain.
> chore(docs): remove links to deprecated spectrum community

- src/endpoints/Files.js
- tests/endpoints/Files.test.js
Ran into an issue today where a file export was failing because it was taking ~45 seconds and for some reason there's a timeout imposed client-side for the `api` transport. I think we should be ok to increase this timeout or remove it altogether. I've increased it to 5 minutes in hopes to unblock a customer.
> fix: increase file export timeout for api transport

- CHANGELOG.md
- abstract-sdk.d.ts
- docs/configuration.md
- package.json
- src/endpoints/Activities.js
- src/endpoints/Assets.js
- src/endpoints/Branches.js
- src/endpoints/Changesets.js
- src/endpoints/CollectionLayers.js
- src/endpoints/Collections.js
- src/endpoints/Comments.js
- src/endpoints/Commits.js
- src/endpoints/Data.js
- src/endpoints/Descriptors.js
- src/endpoints/Endpoint.js
- src/endpoints/Files.js
- src/endpoints/Layers.js
- src/endpoints/Memberships.js
- src/endpoints/Notifications.js
- src/endpoints/Organizations.js
- src/endpoints/Pages.js
- src/endpoints/Previews.js
- src/endpoints/Projects.js
- src/endpoints/ReviewRequests.js
- src/endpoints/Sections.js
- src/endpoints/Shares.js
- src/endpoints/Stars.js
- src/endpoints/Users.js
- src/endpoints/Webhooks.js
- src/types.js
I have tested locally with `mitmproxy` and it seems work great. I did think about using `node-proxy-fetch` instead to auto-detect proxy config but this suggestion from the issue I think is the most flexible and allows us to keep that configuration out of the actual module itself.
```javascript
const HttpsProxyAgent = require("https-proxy-agent");
const Abstract = require("abstract-sdk");
// change to point to your proxy or use env variable if available
const proxyAgent = new HttpsProxyAgent("http://127.0.0.1:8080");
const client = new Abstract.Client({
proxyAgent,
accessToken,
...etc
});
```
closes #328
> fix: Optional proxy agent param to fetch

- src/endpoints/Assets.js
- src/endpoints/Files.js
this fixes the following crash in `files.raw` endpoint:
```
(node:75718) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '[FILE WITH / IN ITS NAME].sketch'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, …
```
> Fix: export files with / in their names
